[build]
  builder = "docker"

[deploy]
  healthcheckPath = "/health"
  healthcheckTimeout = 10
  restartPolicyMaxRetries = 5

[service]
  name = "jobs-scout"

[variable]
  TZ = "Europe/Madrid"

[volume]
  name = "data"
  mountPath = "/app/data"
